import type { Client } from "./types";

export const DEFAULT_SETUP_FEE = 1500;
export const DEFAULT_MONTHLY_FEE = 249;

export const demoClients: Client[] = [
  {
    id: "client-1",
    company: "Summit Logistics",
    contactName: "Rachel Torres",
    email: "rachel@summitlogistics.com",
    phone: "(503) 555-0142",
    status: "active",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "full",
    completedSteps: [
      "requirements-submitted",
      "scope-pricing-confirmed",
      "setup-payment-received",
      "dashboard-ready",
      "active",
    ],
    onboardingFormStatus: "submitted",
    scopePricingConfirmedAt: "2025-08-05T10:00:00Z",
    setupPaidAmount: 1500,
    subscriptionActive: true,
    dashboardUrl: "https://dashboard.example.com/summit-logistics",
    payments: [
      {
        id: "p1",
        date: "2025-08-12T10:00:00Z",
        amount: 1500,
        type: "setup",
        note: "Full setup fee",
      },
      {
        id: "p2",
        date: "2025-09-01T09:00:00Z",
        amount: 249,
        type: "subscription",
      },
      {
        id: "p3",
        date: "2025-10-01T09:00:00Z",
        amount: 249,
        type: "subscription",
      },
    ],
    notes: [
      {
        id: "n1",
        date: "2025-08-15T14:00:00Z",
        content: "Dashboard configured with fleet tracking widgets.",
      },
    ],
    files: [
      {
        id: "f1",
        name: "Summit-brand-guidelines.pdf",
        type: "PDF",
        addedAt: "2025-08-10T12:00:00Z",
      },
    ],
    createdAt: "2025-08-01T08:00:00Z",
  },
  {
    id: "client-2",
    company: "Harbor & Co. Realty",
    contactName: "James Whitfield",
    email: "james@harborco.com",
    phone: "(617) 555-0198",
    status: "active",
    setupFee: 2000,
    monthlyFee: 299,
    onboardingPath: "payment-only",
    completedSteps: ["setup-payment-received", "dashboard-ready", "active"],
    setupPaidAmount: 2000,
    subscriptionActive: true,
    dashboardUrl: "https://dashboard.example.com/harbor-co",
    payments: [
      {
        id: "p4",
        date: "2025-09-05T11:00:00Z",
        amount: 2000,
        type: "setup",
        note: "Custom pricing — premium package",
      },
      {
        id: "p5",
        date: "2025-10-01T09:00:00Z",
        amount: 299,
        type: "subscription",
      },
    ],
    notes: [],
    files: [],
    createdAt: "2025-09-01T08:00:00Z",
  },
  {
    id: "client-3",
    company: "Greenleaf Organics",
    contactName: "Priya Sharma",
    email: "priya@greenleaforganics.co",
    phone: "(415) 555-0176",
    status: "pending",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "full",
    completedSteps: ["requirements-submitted"],
    setupPaidAmount: 0,
    subscriptionActive: false,
    onboardingFormStatus: "submitted",
    onboardingSubmission: {
      company: "Greenleaf Organics",
      contactName: "Priya Sharma",
      email: "priya@greenleaforganics.co",
      phone: "(415) 555-0176",
      businessDescription: "Organic produce delivery and retail.",
      dashboardGoals: "Track orders, inventory, and delivery performance.",
      selectedTools: ["google-sheets", "stripe"],
      submittedAt: "2025-09-30T14:00:00Z",
    },
    payments: [],
    notes: [
      {
        id: "n2",
        date: "2025-10-01T16:00:00Z",
        content: "Awaiting scope review before sending payment link.",
      },
    ],
    files: [],
    createdAt: "2025-09-28T10:00:00Z",
  },
  {
    id: "client-4",
    company: "Atlas Manufacturing",
    contactName: "Marcus Chen",
    email: "marcus@atlasmfg.com",
    phone: "(312) 555-0133",
    status: "pending",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "full",
    completedSteps: [
      "requirements-submitted",
      "scope-pricing-confirmed",
    ],
    setupPaidAmount: 750,
    onboardingFormStatus: "submitted",
    scopePricingConfirmedAt: "2025-10-01T10:00:00Z",
    acceptedSourcesIn: ["QuickBooks Online", "Excel / CSV"],
    acceptedScreens: ["Production overview", "Job costing"],
    onboardingSubmission: {
      company: "Atlas Manufacturing",
      contactName: "Marcus Chen",
      email: "marcus@atlasmfg.com",
      phone: "(312) 555-0133",
      businessDescription: "Custom metal fabrication and assembly.",
      dashboardGoals: "Production throughput, job costing, and backlog visibility.",
      reportingPainPoints: "Data spread across spreadsheets and shop floor logs.",
      selectedTools: ["excel-csv", "quickbooks"],
      submittedAt: "2025-09-25T11:00:00Z",
    },
    subscriptionActive: false,
    payments: [
      {
        id: "p6",
        date: "2025-10-03T13:00:00Z",
        amount: 750,
        type: "setup",
        note: "Partial setup payment (50%)",
      },
    ],
    notes: [
      {
        id: "n3",
        date: "2025-10-03T13:30:00Z",
        content: "Client requested split payment — second half due Oct 17.",
      },
    ],
    files: [],
    createdAt: "2025-09-20T08:00:00Z",
  },
  {
    id: "client-5",
    company: "Coastal Events Group",
    contactName: "Elena Vasquez",
    email: "elena@coastalevents.com",
    phone: "(305) 555-0167",
    status: "pending",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "payment-only",
    completedSteps: ["setup-payment-received"],
    setupPaidAmount: 1500,
    subscriptionActive: false,
    payments: [
      {
        id: "p7",
        date: "2025-10-05T10:00:00Z",
        amount: 1500,
        type: "setup",
      },
    ],
    notes: [],
    files: [],
    createdAt: "2025-10-02T09:00:00Z",
  },
  {
    id: "client-6",
    company: "Northwind Consulting",
    contactName: "David Park",
    email: "david@northwind.io",
    phone: "(206) 555-0189",
    status: "pending",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "full",
    completedSteps: [],
    setupPaidAmount: 0,
    subscriptionActive: false,
    onboardingFormStatus: "not-started",
    payments: [],
    notes: [],
    files: [],
    createdAt: "2025-10-06T11:00:00Z",
  },
  {
    id: "client-7",
    company: "Vintage Paper Co.",
    contactName: "Sophie Laurent",
    email: "sophie@vintagepaper.co",
    phone: "(718) 555-0154",
    status: "archived",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "full",
    completedSteps: [
      "requirements-submitted",
      "scope-pricing-confirmed",
      "setup-payment-received",
      "dashboard-ready",
      "active",
    ],
    onboardingFormStatus: "submitted",
    scopePricingConfirmedAt: "2025-08-05T10:00:00Z",
    setupPaidAmount: 1500,
    subscriptionActive: false,
    dashboardUrl: "https://dashboard.example.com/vintage-paper",
    payments: [
      {
        id: "p8",
        date: "2024-06-10T10:00:00Z",
        amount: 1500,
        type: "setup",
      },
      {
        id: "p9",
        date: "2024-07-01T09:00:00Z",
        amount: 249,
        type: "subscription",
      },
      {
        id: "p10",
        date: "2025-03-15T14:00:00Z",
        amount: 100,
        type: "refund",
        note: "Prorated refund on cancellation",
      },
    ],
    notes: [
      {
        id: "n4",
        date: "2025-03-14T10:00:00Z",
        content: "Client cancelled subscription — business closed.",
      },
    ],
    files: [],
    createdAt: "2024-06-01T08:00:00Z",
  },
  {
    id: "client-8",
    company: "Alpine Comfort HVAC",
    contactName: "Jordan Ellis",
    email: "jordan@alpinecomforthvac.com",
    phone: "(303) 555-0122",
    status: "pending",
    setupFee: 1500,
    monthlyFee: 249,
    onboardingPath: "full",
    completedSteps: ["requirements-submitted", "scope-pricing-confirmed"],
    onboardingFormStatus: "submitted",
    scopePricingConfirmedAt: "2025-10-10T14:00:00Z",
    setupPaidAmount: 750,
    subscriptionActive: false,
    agreedScopeSummary:
      "Operations dashboard: payments received, open invoices, and field schedule from QuickBooks Online and Google Calendar.",
    acceptedSourcesIn: ["QuickBooks Online", "Google Calendar"],
    acceptedScreens: ["Operations overview", "Receivables", "Schedule"],
    adminCompletedMilestones: ["discovery", "guided-data-setup", "building"],
    guidedConnections: [
      {
        id: "conn-alpine-qbo",
        label: "QuickBooks Online",
        demoStatus: "connected",
      },
      {
        id: "conn-alpine-cal",
        label: "Google Calendar",
        demoStatus: "data-validated",
      },
    ],
    buildStatusNote:
      "Sample preview below uses agreed metrics. Final wiring follows your review.",
    dashboardPreviewUrl: "https://preview.example.com/alpine-hvac",
    onboardingSubmission: {
      company: "Alpine Comfort HVAC",
      contactName: "Jordan Ellis",
      email: "jordan@alpinecomforthvac.com",
      phone: "(303) 555-0122",
      businessDescription: "Residential and light commercial HVAC service.",
      dashboardGoals:
        "See cash collected, open invoices, and technician schedule without switching apps.",
      selectedTools: ["quickbooks", "google-calendar"],
      submittedAt: "2025-10-08T16:00:00Z",
    },
    payments: [
      {
        id: "p-alpine-1",
        date: "2025-10-12T10:00:00Z",
        amount: 750,
        type: "setup",
        note: "Setup deposit (50%)",
      },
    ],
    notes: [],
    files: [],
    createdAt: "2025-10-05T09:00:00Z",
  },
  {
    id: "client-9",
    company: "Meridian Home Goods",
    contactName: "Avery Chen",
    email: "avery@meridianhomegoods.com",
    phone: "(512) 555-0191",
    status: "pending",
    setupFee: 1800,
    monthlyFee: 279,
    onboardingPath: "full",
    completedSteps: ["requirements-submitted", "scope-pricing-confirmed", "setup-payment-received"],
    onboardingFormStatus: "submitted",
    scopePricingConfirmedAt: "2025-10-06T11:00:00Z",
    setupPaidAmount: 1800,
    subscriptionActive: false,
    agreedScopeSummary:
      "Retail performance view: weekly sales from Google Sheets and pipeline summary from HubSpot.",
    acceptedSourcesIn: ["Google Sheets", "HubSpot"],
    acceptedScreens: ["Sales pulse", "Pipeline snapshot"],
    adminCompletedMilestones: ["discovery"],
    guidedConnections: [
      {
        id: "conn-meridian-sheets",
        label: "Google Sheets",
        demoStatus: "awaiting-authorization",
      },
      {
        id: "conn-meridian-hubspot",
        label: "HubSpot",
        demoStatus: "not-started",
      },
    ],
    guidedSetupNotes: "Discovery completed — scheduling guided Sheet + HubSpot sessions.",
    onboardingSubmission: {
      company: "Meridian Home Goods",
      contactName: "Avery Chen",
      email: "avery@meridianhomegoods.com",
      phone: "(512) 555-0191",
      businessDescription: "Boutique home goods with two retail locations.",
      dashboardGoals: "Weekly sales trends and marketing pipeline in one morning view.",
      selectedTools: ["google-sheets", "hubspot"],
      submittedAt: "2025-10-04T13:00:00Z",
    },
    payments: [
      {
        id: "p-meridian-1",
        date: "2025-10-08T09:00:00Z",
        amount: 1800,
        type: "setup",
        note: "Full setup fee",
      },
    ],
    notes: [],
    files: [],
    createdAt: "2025-10-01T10:00:00Z",
  },
];
